name: On pull request to main

on:
  pull_request:
    branches:
      - main

concurrently:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-lint-test:
    name: Lint and test python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./github/actions/lint-test-python
