name: On pull request to main

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  SOURCE_DIRECTORY: "."

jobs:
  python-lint-test:
    name: Lint and test python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/get-versions-from-poetry
        id: get-versions
        with:
          working-directory: ${{ env.SOURCE_DIRECTORY }}

      - shell: bash
        run: |
          echo "${{ steps.get-versions.outputs.python-version }}"
          echo "${{ steps.get-versions.outputs.poetry-version }}"

      - uses: ./.github/actions/lint-test-python
        with:
          python-version: ${{ steps.get-versions.outputs.python-version }}
          poetry-version: ${{ steps.get-versions.outputs.poetry-version }}
          working-directory: ${{ env.SOURCE_DIRECTORY }}
