name: On push main
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  SOURCE_DIRECTORY: "."

jobs:
  version-tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v4
    - id: tag_version
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

  publish-python-package:
    runs-on: ubuntu-latest
    needs:
      - version-tag
    steps:
      - uses: actions/checkout@v4

      - id: get-versions
        uses: ./.github/actions/get-versions-from-poetry
        with:
          working-directory: ${{ github.event.inputs.working-directory }}

      - name: Set version in pyproject.toml
        shell: bash
        run: |
          sed -i -E '/^\[tool\.poetry\]/,/^\[/ s/version = "[^"]+"/version = "${{ needs.version-tag.outputs.new_tag }}"/' ${{ env.SOURCE_DIR }}/pyproject.toml

      - name: Validate version is set in pyproject.toml
        shell: bash
        run: |
          if ! grep -q 'version = "${{ needs.version-tag.outputs.new_tag }}"' ${{ inputs.directory-where-pyproject-toml-lives }}/pyproject.toml; then
            echo "Version in pyproject.toml is not updated to ${{ inputs.version }}"
            exit 1
          fi

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          python-version: ${{ steps.get-versions.outputs.python-version }}
          poetry-version: ${{ steps.get-versions.outputs.poetry-version }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          build_format: "sdist"
          ignore_dev_requirements: "yes"
