name: On push main
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  SOURCE_DIRECTORY: "."

jobs:
  tag-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          DEFAULT_BUMP: minor
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
      - id: print_tag
        run: echo "The new tag is ${{ steps.tag_version.outputs.new_tag }}"

  publish-python-package:
    runs-on: ubuntu-latest
    needs:
      - tag-version
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/get-versions-from-poetry
        id: get-versions
        with:
          working-directory: ${{ env.SOURCE_DIRECTORY }}

      - name: Set version in pyproject.toml
        shell: bash
        run: |
          echo "Setting version in pyproject.toml to ${{ needs.tag-version.outputs.new_tag }}"
          sed -i -E '/^\[tool\.poetry\]/,/^\[/ s/version = "[^"]+"/version = "${{ needs.tag-version.outputs.new_tag }}"/' pyproject.toml

      - name: Validate version is set in pyproject.toml
        shell: bash
        run: |
          if ! grep -q 'version = "${{ needs.tag-version.outputs.new_tag }}"' pyproject.toml; then
            echo "Version in pyproject.toml is not updated to ${{ inputs.version }}"
            exit 1
          fi

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Load cached poetry
        uses: actions/cache@v3
        with:
          path: ~/.local/
          key: poetry-cache-${{ steps.setup-python.outputs.python-version }}-${{ inputs.poetry-version }}

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ inputs.poetry-version }}
          virtualenvs-in-project: true

      - name: Verify Poetry dependencies
        working-directory: ${{ inputs.working-directory }}
        run: poetry check --lock
        shell: bash

      - name: Load cached virtualenv
        id: cached-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles(format('{0}/poetry.lock', inputs.poetry-version)) }}
          restore-keys: |
            venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-

      - name: Install build dependencies
        if: steps.cached-dependencies.outputs.cache-hit != 'true'
        run: poetry install --without dev --sync

      - name: Publish to pypi
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          password: ${{ secrets.PYPI_TOKEN }}

#      - name: Build and publish to pypi
#        uses: JRubics/poetry-publish@v1.17
#        with:
#          python_version: ${{ steps.get-versions.outputs.python-version }}
#          poetry_version: ${{ steps.get-versions.outputs.poetry-version }}
#          pypi_token: ${{ secrets.PYPI_TOKEN }}
#          build_format: "sdist"
#          ignore_dev_requirements: "yes"
